[package]
name = "ix-match"
authors = ["Taylor Denouden <taylor.denouden@hakai.org>"]
version = "0.2.1"
edition = "2021"
repository = "https://github.com/tayden/ix-match"
description = "A tool for matching and moving IIQ files so they can be easily imported into IX Capture."
license = "MIT"
readme = "README.md"

[dependencies]
polars = { version = "0.42.0", features = ["polars-ops", "asof_join", "dtype-datetime", "lazy"] }
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
glob = "0.3.1"
anyhow = "1.0.86"
